version: '3'

services:

  app:
    container_name: drone-ci-proxy
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      WEB_PORT: ${WEB_PORT}
      TARGET_HOST: ${TARGET_HOST}
    volumes:
      - ./:/app
#      - /var/run/docker.sock:/var/run/docker.sock


